= exercism-kotlin
:toc:

== general information

Platform: https://exercism.org/

Public profile: https://exercism.org/profiles/marcosDLCS

Kotlin Track: https://exercism.org/tracks/kotlin

=== what is kotlin?

Kotlin was designed and developed by JetBrains, the company behind IntelliJ. It is a language that runs on the JVM which can target versions 6+ (including the Android platform). JetBrains wanted to use a statically typed language which can remove Java boilerplate code, provide modern functional paradigms, and had seamless two-way Java interoperability with their existing codebase. The JVM already had alternate languages like Groovy and Scala but neither fit the bill with their desired criteria, so they built Kotlin.

Kotlin syntax is similar to Scala and Swift but pulls in the best-of-breed features from other languages such as C# and Groovy. Kotlin took a pragmatic approach at features included in the language by only providing functionality that has been proven to be useful for developers. With this decision they implemented a subset of features of Scala with the intent that it will provide more maintainable code with an easier learning curve for developers looking for a "better Java".

JetBrains has a dedicated team of developers working on Kotlin with the codebase available on Github.

Official page: https://kotlinlang.org/

Official docs: https://kotlinlang.org/docs/home.html

== ongoing

List of _ongoing_ exercises:

=== *easy*

* link:./scale-generator[scale-generator]

=== *medium*

* link:./beer-song[beer-song]
* link:./word-count[word-count]

=== *hard*

* link:./react[react]
* link:./zebra-puzzle[zebra-puzzle]

== completed

List of _completed_ exercises:

=== *easy*

* link:./acronym[acronym]
* link:./armstrong-numbers[armstrong-numbers]
* link:./crypto-square[crypto-square]
* link:./custom-set[custom-set]
* link:./darts/[darts]
* link:./difference-of-squares[difference-of-squares]
* link:./dnd-character[dnd-character]
* link:./gigasecond[gigasecond]
* link:./hamming[hamming]
* link:./hello-world[hello-world]
* link:./leap[leap]
* link:./pangram[pangram]
* link:./perfect-numbers[perfect-numbers]
* link:./protein-translation[protein-translation]
* link:./raindrops[raindrops]
* link:./resistor-color[resistor-color]
* link:./resistor-color-duo[resistor-color-duo]
* link:./resistor-color-trio[resistor-color-trio]
* link:./reverse-string/[reverse-string]
* link:./rna-transcription[rna-transcription]
* link:./run-length-encoding[run-length-encoding]
* link:./scrabble-score[scrabble-score]
* link:./secret-handshake[secret-handshake]
* link:./space-age[space-age]
* link:./transpose[transpose]
* link:./two-fer[two-fer]
* link:./yacht[yacht]

=== *medium*

* link:./matrix[matrix]
* link:./saddle-points[saddle-points]
* link:./triangle[triangle]

=== *hard*

😩
